# Generated by Django 6.1.1 on 2026-09-24 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('lunch_action', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('carditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card.carditem')),
                ('is_vegan', models.BooleanField(default=False)),
            ],
            bases=('card.carditem',),
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('carditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card.carditem')),
                ('is_alcoholic', models.BooleanField(default=False)),
            ],
            bases=('card.carditem',),
        ),
    ]
